name: nested_scroll_views
description: 'Flutter nested scrolling views. A plugin that allows you to make a scrolling view that scrolls a certain number of pages based on the scroll velocity, and then snaps to the nearest scrolling view .'
version: 0.0.9
homepage: https://github.com/hgraceb/nested_scroll_views

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: '>=3.16.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
